   name: Rollback Deployment

   on:
     workflow_dispatch:
       inputs:
         version:
           description: 'Commit SHA to rollback to'
           required: true

   jobs:
     rollback:
       runs-on: ubuntu-latest
       
       steps:
       - name: Checkout specific version
         uses: actions/checkout@v3
         with:
           ref: ${{ github.event.inputs.version }}
       
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '16'
           
       - name: Install dependencies
         run: npm ci
         
       - name: Build project
         run: npm run build
         
       - name: Deploy to Hostinger
         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
         with:
           server: ${{ secrets. ftp.raw.gatvia.com }}
           username: ${{ secrets.u950050130.adminftp }}
           password: ${{ secrets.!@#Acc3ss931 }}
           local-dir: ./build/
           server-dir: ${{ secrets./home/u950050130/domains/raw.gatvia.com/public_html }}